services:
  - type: web
    name: ekomobil-campaign-tool-backend
    env: node
    buildCommand: cd backend && npm ci && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

